# Use root/example as user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 5532:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: postgres
